# First, copy this file to a new one called "application.yml" in the same
# config directory.
# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development.
# Read more about figaro here: https://github.com/laserlemon/figaro
# Note that changes to this file will require a server restart to take effect.
# Each entry sets a local environment variable and overrides ENV variables
# in the Unix shell. For example, setting:
# OHANA_API_ENDPOINT: https://ohana-api-demo.herokuapp.com/api
# makes "https://ohana-api-demo.herokuapp.com/api" available as
# ENV["OHANA_API_ENDPOINT"] in the app. See config/initializers/ohanapi.rb
# for a usage example.

# Set this to the URL for your instance of the Ohana API:
# https://github.com/codeforamerica/ohana-api
# This environment variable is required.
OHANA_API_URL: https://clacks-ohana.herokuapp.com
OHANA_API_ENDPOINT: https://clacks-ohana.herokuapp.com/api

# The "DOMAIN_NAME" environment variable should be set to your app's
# domain name, without the "www" subdomain, unless you're using a Heroku
# domain, in which case you should set it to your full Heroku domain name,
# such as "ohana-web-search-demo.herokuapp.com".
# If you have a custom domain name, like "www.smc-connect.org", that
# means setting it to "smc-connect.org".
#
# In development, it should only be set to a 2-level domain name,
# like "lvh.me", or "myapp.dev" if you're using Pow.
# Translation won't work with "localhost", so please open the site
# locally via http://lvh.me:{port number}
#
# Read more about lvh.me here:
# http://matthewhutchinson.net/2011/1/10/configuring-subdomains-in-development-with-lvhme
# Pow should work too if you prefer that: http://pow.cx/
DOMAIN_NAME: herokuapp.com

# If you choose to turn on rate limiting in your instance of Ohana API,
# obtain an API Token for this app from the developer portal of the API,
# then replace "changeme" with the actual token below.
# OHANA_API_TOKEN: changeme

# TZ
# When you visit a location, for example,
# http://ohana-web-search-demo.herokuapp.com/locations/salvation-army/sunnyvale-corps,
# the 'Last updated' time that is displayed at the bottom right of the page is
# set to UTC by default. If you would like to set it to a more appropriate
# time zone where most of your visitors live, you can set the 'TZ' environment
# variable to one of the accepted values:
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
# For example, to set the time zone to Eastern Time, you would set the 'TZ'
# value below to 'America/New_York'.

# DEFAULT_PER_PAGE
# This setting controls how many results you want to the API to return
# per page by default. Note that clients can set this dynamically via
# the "per_page" parameter, but if "per_page" is not specified, then the
# setting below will dictate how many results are returned.

# MAX PER PAGE
# This setting controls the maximum amount of results you want to the API to
# return per page. If a client sets the "per_page" parameter to a value higher
# than MAX_PER_PAGE, the API will limit results per page to MAX_PER_PAGE.

# FROM_ADDRESS
# This is the address that appears as the from address whenever the application
# sends an email e.g. for flagging/resolving issues.

# SITE_ADMIN_EMAIL
# This is the address of the site admin. This address is copied into any email
# that is sent for flagging/resolving issues.

# PREREQUISITE_CATEGORY
# This is the category that any sevice must be tagged with to be included.
# Leave blank to include all.

# APP_TITLE
# The title of the application, used in the <title> tags.

# APP_DESCRIPTION
# A short description of the application, used in the meta description tag.

# DEFAULT LAT AND LNG
# The default centre point of the map in terms of latitude and longitude.

# SMTP_*** SETTINGS
# These are required for the application to send emails. These are then used
# in the following initializer: '/config/initializers/setup_mail.rb'

# DEFAULT_HOST
# This is so the application can generate full urls rather than paths when required.

# CATEGORIES
# These are the categories that are used to generate the homepage directory and
# form filter. Note these must be comma-delimited without
# spaces e.g. 'Learning,Prenatal & Babies,Music & Drama'

development:
  TZ: 'Europe/London'
  DEFAULT_PER_PAGE: '10'
  MAX_PER_PAGE: '20'
  LANG: en_GB.UTF-8
  FROM_ADDRESS: 'giannichan@gmail.com'
  SITE_ADMIN_EMAIL: 'giannichan@gmail.com'
  PREREQUISITE_CATEGORY: 'Clackskids'
  APP_TITLE: 'Clackskids'
  APP_DESCRIPTION: 'Clackskids helps you browse childcare and parenting support services in the Clackmannanshire area.'
  DEFAULT_LAT: '56.11'
  DEFAULT_LNG: '-3.74'
  SMTP_PORT: '587'
  SMTP_ADDRESS: 'smtp.servername.com'
  SMTP_DOMAIN: 'servername.com'
  SMTP_USER_NAME: 'username'
  SMTP_PASSWORD: 'password'
  SMTP_AUTHENTICATION: 'plain'
  DEFAULT_HOST: '127.0.0.1:3000'
  CATEGORIES: 'Childcare,Clubs,Sport,Support,Health,Learning,Prenatal & Babies,Music & Drama'
  USE_AGE_RANGE: true
  STRAPLINE: 'A better future for every child'

production:
  TZ: 'Europe/London'
  DEFAULT_PER_PAGE: '30'
  MAX_PER_PAGE: '50'
  LANG: en_GB.UTF-8
  FROM_ADDRESS: 'noreply@clacksweb.org.uk'
  SITE_ADMIN_EMAIL: 'giannichan@gmail.com'
  PREREQUISITE_CATEGORY: 'Clackskids'
  APP_TITLE: 'Clackskids'
  APP_DESCRIPTION: 'Clackskids helps you browse childcare and parenting support services in the Clackmannanshire area.'
  DEFAULT_LAT: '56.11'
  DEFAULT_LNG: '-3.74'
  SMTP_PORT: '587'
  SMTP_ADDRESS:
  SMTP_DOMAIN:
  SMTP_USER_NAME:
  SMTP_PASSWORD:
  SMTP_AUTHENTICATION: 'plain'
  DEFAULT_HOST: 'clackskids.herokuapp.com'
  CATEGORIES: 'Childcare,Clubs,Sport,Support,Health,Learning,Prenatal & Babies,Music & Drama'
  USE_AGE_RANGE: true
  STRAPLINE: 'A better future for every child'

# If you are using a custom domain name, set CANONICAL_URL to your preferred
# domain name, such as 'example.org' or 'www.example.org'.
# See config/environments/production.rb for more details.
# CANONICAL_URL:

###############################################################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
#
###############################################################################
test:
  DEFAULT_PER_PAGE: '30'
  MAX_PER_PAGE: '50'
  LANG: en_GB.UTF-8
  FROM_ADDRESS: 'giannichan@gmail.com'
  SITE_ADMIN_EMAIL: 'giannichan@gmail.com'
  PREREQUISITE_CATEGORY: 'Clackskids'
  APP_TITLE: 'Clackskids'
  APP_DESCRIPTION: 'Clackskids helps you browse childcare and parenting support services in the Clackmannanshire area.'
  DEFAULT_LAT: '56.11'
  DEFAULT_LNG: '-3.74'
  SMTP_PORT: '587'
  SMTP_ADDRESS: 'smtp.servername.com'
  SMTP_DOMAIN: 'servername.com'
  SMTP_USER_NAME: 'username'
  SMTP_PASSWORD: 'password'
  SMTP_AUTHENTICATION: 'plain'
  DEFAULT_HOST: '127.0.0.1:3000'
  CATEGORIES: 'Childcare,Clubs,Sport,Support,Health,Learning,Prenatal & Babies,Music & Drama'
  USE_AGE_RANGE: true
  STRAPLINE: 'A better future for every child'

#OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
#OHANA_API_TOKEN: ~
#DOMAIN_NAME: lvh.me